# Site settings
title: "Agnivesh Patel"
description: "Web Developer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Agnivesh Patel"
resume_title:                   "Web Developer"
resume_contact_email:           "agniveshpatel@gmail.com"
resume_contact_telephone:       "+91 83180 92773"
resume_contact_address:         "Bengaluru, India"
resume_header_contact_info: "Bengaluru, India | +91 83180 92773 | agniveshpatel@gmail.com"
resume_header_intro: "<p>Seeking a full time job preferably working with ReactJS or Ruby on Rails for Frontend or Full-Stack positions. Looking forward to working with a dynamic team, building next generation of web apps.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/agni21"
#  resume_stackoverflow_url:     "https://stackoverflow.com/users/5228689/agni10"
  resume_twitter_url:           "http://twitter.com/agniveshpatel"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/agniveshpatel/"
  # resume_instagram_url:         "insert your Instagram URL here"
#  resume_website_url:           "http://agnivesh.me"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
